import React, { useState, useEffect } from 'react';
import {
  Zap,
  Binary,
  Cpu,
  HardDriveDownload,
  MoveRight,
  X,
  Github,
  Linkedin,
  Twitter,
  Book,
  Flame,
  Atom,
  BookOpen,
  Menu,
  Home,
  Compass,
  Layers3,
  Sparkles,
  Wand2,
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import NebulaBackground from './NebulaBackground';
import { useMotionPolicy } from '../hooks/useMotionPolicy';

// Types and Interfaces
interface LandingPageProps {
  onLogin: () => void;
  onGetStarted: () => void;
  onSubscribe?: () => void;
  onShowAbout?: () => void;
  onShowTerms?: () => void;
  onShowPrivacy?: () => void;
  onShowCompliance?: () => void;
  onShowDisclaimer?: () => void;
  onShowBlog?: () => void;
}

// Data Constants
const DEMO_BOOKS = [
  {
    id: 'street',
    input: 'Stop Overthinking & Take Action',
    title: '"Burn the Boat: No More \'Someday\' Shit"',
    shortTitle: 'Burn the Boat',
    subtitle: "No More 'Someday' Shit",
    desc: 'A raw, aggressive take on crushing debt and stacking assets. Generated by Street Mode AI.',
    mode: 'Street Mode',
    engineDesc: 'High-energy, direct, and action-oriented. Perfect for motivation and rapid consumption.',
    words: '19,914',
    chapters: '10',
    url: 'https://cdn.jsdelivr.net/gh/tanmay-kalbande/pustakam-cdn@main/demo-books/Burn_The_Boat_No_More_Someday_Shit.pdf',
    gradient: 'from-cyan-900/40 to-blue-900/40',
    chapterList: ['Burn the Boat', 'Overthinking is Cancer', 'Fear as a Compass', 'The Cost of Delay'],
  },
  {
    id: 'stellar',
    input: 'Personal Finance for Young Adults',
    title: '"Architecting Wealth: A Scientific Framework for Financial Growth"',
    shortTitle: 'Wealth Design',
    subtitle: 'Foundations & Mastery',
    desc: 'A structured, formal guide to financial systems and long-term equity. Generated by Stellar Mode AI.',
    mode: 'Stellar Mode',
    engineDesc: 'Academic, thorough, and highly structured. Ideal for complex topics and deep learning.',
    words: '24,152',
    chapters: '12',
    url: 'https://cdn.jsdelivr.net/gh/tanmay-kalbande/pustakam-cdn@main/demo-books/Foundations_Of_Personal_Finance.pdf',
    gradient: 'from-purple-900/40 to-indigo-900/40',
    chapterList: ['The Hidden Tax', 'Compound Mastery', 'Asset Allocation', 'The Wealth Flywheel'],
  },
];

// Animation Constants (Ported from Code 2)
const TAB_ORDER = ['home', 'process', 'street', 'stellar', 'demo', 'features'];

const colorStyles: Record<string, { chip: string; border: string; icon: string }> = {
  cyan: {
    chip: 'bg-cyan-500/10',
    border: 'border-cyan-500/15',
    icon: 'text-cyan-400/90',
  },
  purple: {
    chip: 'bg-purple-500/10',
    border: 'border-purple-500/15',
    icon: 'text-purple-400/90',
  },
  emerald: {
    chip: 'bg-emerald-500/10',
    border: 'border-emerald-500/15',
    icon: 'text-emerald-400/90',
  },
};
const processCardStyles: Record<string, { step: string; chip: string; border: string; icon: string }> = {
  cyan: {
    step: 'text-cyan-400/40',
    chip: 'bg-cyan-500/[0.08]',
    border: 'border-cyan-500/20',
    icon: 'text-cyan-400/90',
  },
  purple: {
    step: 'text-purple-400/40',
    chip: 'bg-purple-500/[0.08]',
    border: 'border-purple-500/20',
    icon: 'text-purple-400/90',
  },
  amber: {
    step: 'text-amber-400/40',
    chip: 'bg-amber-500/[0.08]',
    border: 'border-amber-500/20',
    icon: 'text-amber-400/90',
  },
  emerald: {
    step: 'text-emerald-400/40',
    chip: 'bg-emerald-500/[0.08]',
    border: 'border-emerald-500/20',
    icon: 'text-emerald-400/90',
  },
};

const desktopVariants = {
  enter: (dir: number) => ({
    opacity: 0,
    x: dir * 50,
    scale: 0.97,
  }),
  center: {
    opacity: 1,
    x: 0,
    scale: 1,
    transition: { duration: 0.38, ease: [0.25, 0.46, 0.45, 0.94] },
  },
  exit: (dir: number) => ({
    opacity: 0,
    x: dir * -35,
    scale: 0.97,
    transition: { duration: 0.24, ease: [0.55, 0, 1, 0.45] },
  }),
};

const LandingPage = ({
  onLogin,
  onGetStarted,
  onSubscribe,
  onShowAbout,
  onShowTerms,
  onShowPrivacy,
  onShowCompliance,
  onShowDisclaimer,
  onShowBlog,
}: LandingPageProps) => {
  const [activeTab, setActiveTab] = useState<'home' | 'street' | 'stellar' | 'demo' | 'process' | 'features'>('home');
  const [prevTab, setPrevTab] = useState<string>('home'); // Track previous tab for animation direction
  const [showPromo, setShowPromo] = useState(true);
  const [activeDemoIdx, setActiveDemoIdx] = useState(0);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const activeBook = DEMO_BOOKS[activeDemoIdx];
  const { shouldReduceMotion } = useMotionPolicy();

  useEffect(() => {
    const promoDismissed = localStorage.getItem('promo_dismissed');
    if (promoDismissed) {
      setShowPromo(false);
    }
  }, []);

  const handleDismissPromo = () => {
    setShowPromo(false);
    localStorage.setItem('promo_dismissed', 'true');
  };

  const handleTabChange = (tab: any) => {
    setPrevTab(activeTab); // Set previous before updating active
    setActiveTab(tab);
    setMobileMenuOpen(false);
  };

  // Calculate animation direction
  const getDirection = () => {
    if (shouldReduceMotion) return 0;
    const from = TAB_ORDER.indexOf(prevTab);
    const to = TAB_ORDER.indexOf(activeTab);
    return to >= from ? 1 : -1;
  };

  const landingDesktopVariants = shouldReduceMotion
    ? {
      enter: { opacity: 1, x: 0, scale: 1 },
      center: { opacity: 1, x: 0, scale: 1, transition: { duration: 0 } },
      exit: { opacity: 1, x: 0, scale: 1, transition: { duration: 0 } },
    }
    : desktopVariants;

  // --- SUB-RENDERERS ---

  const renderContent = () => {
    switch (activeTab) {
      case 'street':
        return (
          <div
            key="street"
            className="flex flex-col items-center justify-center min-h-full text-center px-4 w-full max-w-5xl mx-auto py-6"
          >
            <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-full pb-2 md:hidden">
              <span className="text-[10px] font-semibold uppercase tracking-[0.22em] text-cyan-400/50" style={{ fontFamily: "'Rubik', sans-serif" }}>
                Street Mode
              </span>
            </div>
            <div className="w-12 h-12 md:w-14 md:h-14 rounded-2xl bg-cyan-500/10 border border-cyan-500/20 flex items-center justify-center mb-4 md:mb-5 shadow-[0_0_30px_rgba(6,182,212,0.15)] ">
              <Flame className="w-6 h-6 md:w-7 md:h-7 text-cyan-400 drop-shadow-[0_0_12px_rgba(6,182,212,0.5)]" strokeWidth={1.5} />
            </div>
            <h1 className="text-3xl md:text-5xl font-semibold tracking-tight text-white mb-1 md:mb-2 drop-shadow-xl" style={{ fontFamily: "'Rubik', sans-serif" }}>
              Street Mode
            </h1>
            <p className="text-[10px] md:text-lg text-cyan-400 font-medium tracking-wide mb-4 md:mb-6 drop-shadow-[0_0_10px_rgba(6,182,212,0.2)]">
              Action Oriented • Raw • Direct
            </p>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-2 md:gap-5 text-left max-w-4xl w-full mb-6 md:mb-10">
              {[
                { title: 'No-BS Tone', desc: 'Raw and direct language.' },
                { title: 'Execution', desc: 'Action over theory.' },
                { title: 'High Energy', desc: 'Immediate action focus.' },
              ].map((item, i) => (
                <div
                  key={i}
                  className="bg-white/5 border border-white/10 rounded-xl p-2.5 md:p-5 hover:bg-white/[0.07] transition-colors hover:border-cyan-500/30 group"
                >
                  <h3 className="text-cyan-400 font-bold mb-0.5 md:mb-1 uppercase tracking-wide text-[8px] md:text-[10px] group-hover:text-cyan-300 transition-colors">
                    {item.title}
                  </h3>
                  <p className="text-white/60 text-[10px] md:text-[13px] leading-tight md:leading-relaxed group-hover:text-white/80 transition-colors">
                    {item.desc}
                  </p>
                </div>
              ))}
            </div>

            <button
              onClick={onGetStarted}
              className="px-6 py-2 md:px-7 md:py-2.5 bg-cyan-500/10 hover:bg-cyan-500/20 border border-cyan-500/20 hover:border-cyan-500/40 rounded-full text-[11px] md:text-[13px] font-medium tracking-wide text-cyan-400 hover:text-cyan-300 transition-all group flex items-center gap-2 shadow-[0_0_20px_rgba(6,182,212,0.1)]"
            >
              <span>Start Street Mode</span>
              <MoveRight className="w-3 h-3 md:w-3.5 md:h-3.5 group-hover:translate-x-1 transition-transform" />
            </button>
          </div>
        );

      case 'stellar':
        return (
          <div
            key="stellar"
            className="flex flex-col items-center justify-center min-h-full text-center px-4 w-full max-w-5xl mx-auto py-6"
          >
            <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-full pb-2 md:hidden">
              <span className="text-[10px] font-semibold uppercase tracking-[0.22em] text-purple-400/50" style={{ fontFamily: "'Rubik', sans-serif" }}>
                Stellar Mode
              </span>
            </div>
            <div className="w-12 h-12 md:w-14 md:h-14 rounded-2xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center mb-4 md:mb-5 shadow-[0_0_30px_rgba(168,85,247,0.15)]">
              <Atom className="w-6 h-6 md:w-7 md:h-7 text-purple-400 drop-shadow-[0_0_12px_rgba(168,85,247,0.5)] animate-[spin_10s_linear_infinite]" strokeWidth={1.5} />
            </div>
            <h1 className="text-3xl md:text-5xl font-semibold tracking-tight text-white mb-1 md:mb-2 drop-shadow-xl" style={{ fontFamily: "'Rubik', sans-serif" }}>
              Stellar Mode
            </h1>
            <p className="text-[10px] md:text-lg text-purple-400 font-medium tracking-wide mb-4 md:mb-6 drop-shadow-[0_0_10px_rgba(168,85,247,0.2)]">
              Deep Learning • Academic • Structured
            </p>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-2 md:gap-5 text-left max-w-4xl w-full mb-6 md:mb-10">
              {[
                { title: 'Structure', desc: 'Quizzes like a textbook.' },
                { title: 'Mastery', desc: 'Deep mental models.' },
                { title: 'Thorough', desc: 'Covers context and history.' },
              ].map((item, i) => (
                <div
                  key={i}
                  className="bg-white/5 border border-white/10 rounded-xl p-2.5 md:p-5 hover:bg-white/[0.07] transition-colors hover:border-purple-500/30 group"
                >
                  <h3 className="text-purple-400 font-bold mb-0.5 md:mb-1 uppercase tracking-wide text-[8px] md:text-[10px] group-hover:text-purple-300 transition-colors">
                    {item.title}
                  </h3>
                  <p className="text-white/60 text-[10px] md:text-[13px] leading-tight md:leading-relaxed group-hover:text-white/80 transition-colors">
                    {item.desc}
                  </p>
                </div>
              ))}
            </div>

            <button
              onClick={onGetStarted}
              className="px-6 py-2 md:px-7 md:py-2.5 bg-purple-500/10 hover:bg-purple-500/20 border border-purple-500/20 hover:border-purple-500/40 rounded-full text-[11px] md:text-[13px] font-medium tracking-wide text-purple-400 hover:text-purple-300 transition-all group flex items-center gap-2 shadow-[0_0_20px_rgba(168,85,247,0.1)]"
            >
              <span>Start Stellar Mode</span>
              <MoveRight className="w-3 h-3 md:w-3.5 md:h-3.5 group-hover:translate-x-1 transition-transform" />
            </button>
          </div>
        );

      case 'process':
        return (
          <div key="process" className="flex flex-col items-center justify-center min-h-full text-center px-4 w-full max-w-6xl mx-auto py-6">
            <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-full pb-2 md:hidden">
              <span className="text-[10px] font-semibold uppercase tracking-[0.22em] text-cyan-400/50" style={{ fontFamily: "'Rubik', sans-serif" }}>
                Process
              </span>
            </div>
            <div className="text-center mb-4 md:mb-8">
              <span className="text-[8px] md:text-[9px] tracking-[0.4em] uppercase text-cyan-400 mb-1 md:mb-2 block opacity-80 font-semibold">
                The Process
              </span>
              <h2 className="text-2xl md:text-5xl font-bold tracking-tighter text-white drop-shadow-lg" style={{ fontFamily: "'Rubik', sans-serif" }}>
                Your Learning Journey
              </h2>
            </div>

            <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 md:gap-5 w-full max-w-5xl">
              {[
                { step: '01', title: 'Vision', desc: 'Seed your core concept', icon: Zap, color: 'cyan' },
                { step: '02', title: 'Mapping', desc: 'Architect the tone', icon: Binary, color: 'purple' },
                { step: '03', title: 'Synthesis', desc: 'Building your base', icon: Cpu, color: 'amber' },
                { step: '04', title: 'Export', desc: 'Extract your PDF', icon: HardDriveDownload, color: 'emerald' },
              ].map((item, idx) => {
                const style = processCardStyles[item.color];
                return (
                  <div
                    key={idx}
                    className="bg-[#050505]/60 border border-white/10 rounded-2xl md:rounded-[24px] px-3 py-4 md:px-5 md:py-7 flex flex-col items-center justify-center text-center hover:border-white/20 transition-all duration-500 group relative overflow-hidden hover:bg-white/[0.03] backdrop-blur-sm"
                  >
                    <div className={`absolute top-2 right-2 text-[8px] font-mono font-bold ${style.step}`}>{item.step}</div>
                    <div className={`w-8 h-8 md:w-12 md:h-12 rounded-xl border flex items-center justify-center mb-2 md:mb-4 group-hover:scale-110 transition-transform duration-500 ${style.chip} ${style.border}`}>
                      <item.icon className={`w-4 h-4 md:w-6 md:h-6 ${style.icon}`} strokeWidth={1.5} />
                    </div>
                    <h3 className="text-white font-medium text-[9px] md:text-xs mb-1 md:mb-2.5 tracking-widest uppercase opacity-90">{item.title}</h3>
                    <p className="text-white/40 text-[8px] md:text-[10px] leading-tight px-1 md:px-2">{item.desc}</p>
                  </div>
                );
              })}
            </div>

            <div className="mt-10 flex items-center justify-center gap-4 opacity-40">
              <div className="h-px w-10 md:w-14 bg-gradient-to-r from-transparent to-white/30" />
              <span className="text-[8px] md:text-[9px] uppercase tracking-[0.3em] font-light text-white/60 text-center">
                Secure Neural Channels • TLS 1.3
              </span>
              <div className="h-px w-10 md:w-14 bg-gradient-to-l from-transparent to-white/30" />
            </div>
          </div>
        );

      case 'demo':
        return (
          <div key="demo" className="flex flex-col items-center justify-center min-h-full px-4 w-full max-w-5xl mx-auto py-6">
            <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-full pb-2 md:hidden">
              <span className="text-[10px] font-semibold uppercase tracking-[0.22em] text-cyan-400/50" style={{ fontFamily: "'Rubik', sans-serif" }}>
                Demo Preview
              </span>
            </div>
            <div className="w-full space-y-5">
              <div className="flex justify-center gap-2 mb-1">
                {DEMO_BOOKS.map((book, i) => (
                  <button
                    key={book.id}
                    onClick={() => setActiveDemoIdx(i)}
                    className={`px-4 py-2 rounded-full text-[10px] font-semibold uppercase tracking-[0.16em] border transition-all ${i === activeDemoIdx
                      ? 'bg-white text-black border-white'
                      : 'bg-black/40 text-white/60 border-white/15 hover:text-white/85'
                      }`}
                  >
                    {book.mode}
                  </button>
                ))}
              </div>

              <div className="grid md:grid-cols-[1.2fr_1fr] gap-4 md:gap-5 w-full">
                <div className="panel-primary elevation-1 p-5 md:p-6 text-left">
                  <p className="text-[10px] uppercase tracking-[0.22em] text-white/45 mb-3">Live Demo Input</p>
                  <h2 className="text-2xl md:text-4xl font-semibold text-white tracking-tight leading-tight mb-4">{activeBook.input}</h2>
                  <div className="border-l-2 border-white/15 pl-4">
                    <p className="text-[11px] uppercase tracking-[0.18em] text-white/40 mb-1">Generated Output</p>
                    <p className="text-white/80 text-sm md:text-base leading-relaxed">{activeBook.title}</p>
                  </div>
                </div>

                <div className="panel-primary elevation-2 p-4 md:p-5 text-left">
                  <div className="flex items-start gap-4 mb-4">
                    <div className="relative w-20 h-28 md:w-24 md:h-32 rounded-lg border border-white/15 overflow-hidden bg-black/70 flex-shrink-0">
                      <div className="absolute inset-0 bg-[linear-gradient(140deg,#050505_0%,#0f1116_55%,#070707_100%)]" />
                      <div className="absolute left-0 top-0 bottom-0 w-1 bg-white/15" />
                      <div className="relative h-full p-2 flex flex-col justify-between">
                        <span className="text-[7px] text-white/55 uppercase tracking-[0.2em]">Pustakam</span>
                        <span className="text-[10px] leading-tight text-white/90 font-semibold line-clamp-4">{activeBook.shortTitle}</span>
                        <span className="text-[7px] text-white/50 font-mono">Edition 01</span>
                      </div>
                    </div>
                    <div className="flex-1">
                      <div className="text-[10px] uppercase tracking-[0.18em] text-white/40 mb-1">Summary</div>
                      <p className="text-white/70 text-xs md:text-sm leading-relaxed">{activeBook.desc}</p>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-2 mb-4">
                    <div className="panel-secondary p-2.5 text-center">
                      <div className="text-[9px] uppercase tracking-wider text-white/35">Words</div>
                      <div className="text-sm text-white font-semibold">{activeBook.words}</div>
                    </div>
                    <div className="panel-secondary p-2.5 text-center">
                      <div className="text-[9px] uppercase tracking-wider text-white/35">Chapters</div>
                      <div className="text-sm text-white font-semibold">{activeBook.chapters}</div>
                    </div>
                  </div>

                  <a
                    href={activeBook.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="btn-secondary w-full justify-center py-2.5 text-[10px] uppercase tracking-[0.14em]"
                  >
                    <HardDriveDownload className="w-3 h-3" />
                    Download PDF
                  </a>
                </div>
              </div>
            </div>
          </div>
        );

      case 'features':
        return (
          <div key="features" className="flex flex-col items-center justify-center min-h-full px-4 w-full max-w-5xl mx-auto py-6">
            <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-full pb-2 md:hidden">
              <span className="text-[10px] font-semibold uppercase tracking-[0.22em] text-emerald-400/50" style={{ fontFamily: "'Rubik', sans-serif" }}>
                Use Cases
              </span>
            </div>
            <div className="text-center mb-6 md:mb-10">
              <span className="text-[8px] md:text-[9px] tracking-[0.4em] uppercase text-emerald-400 mb-1 md:mb-2 block opacity-80 font-semibold">Capabilities</span>
              <h2 className="text-2xl md:text-5xl font-bold tracking-tighter text-white drop-shadow-lg" style={{ fontFamily: "'Rubik', sans-serif" }}>
                Why Pustakam?
              </h2>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-3 md:gap-5 w-full max-w-5xl">
              {[
                { title: 'Generation', desc: 'Get guides in seconds.', icon: Zap, color: 'cyan' },
                { title: 'Structured', desc: 'Chapters, modules, and quizzes.', icon: Book, color: 'purple' },
                { title: 'Anything', desc: 'Programming to philosophy.', icon: BookOpen, color: 'emerald' },
              ].map((item, i) => (
                <div
                  key={i}
                  className="group relative p-4 md:p-6 rounded-2xl md:rounded-[24px] bg-white/[0.02] border border-white/5 hover:border-white/10 transition-all duration-500 hover:bg-white/[0.04] text-center md:text-left"
                >
                  <div className={`w-8 h-8 md:w-12 md:h-12 rounded-xl md:rounded-2xl flex items-center justify-center mb-3 md:mb-5 border mx-auto md:mx-0 group-hover:scale-110 transition-transform duration-500 ${colorStyles[item.color].chip} ${colorStyles[item.color].border}`}>
                    <item.icon className={`w-4 h-4 md:w-6 md:h-6 ${colorStyles[item.color].icon}`} strokeWidth={1.5} />
                  </div>
                  <h3 className="text-sm md:text-base font-medium mb-1 md:mb-2.5 text-white/90 group-hover:text-white transition-colors">{item.title}</h3>
                  <p className="text-white/40 font-light leading-relaxed text-[11px] md:text-[13px] group-hover:text-white/60 transition-colors">{item.desc}</p>
                </div>
              ))}
            </div>
          </div>
        );

      case 'home':
      default:
        return (
          <div key="home" className="flex flex-col items-center justify-center min-h-full text-center px-4 py-6">
            <div className="relative z-10 max-w-4xl mb-6">
              <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-[200%] pb-2 md:hidden">
                <span className="text-[10px] font-semibold uppercase tracking-[0.22em] text-white/20" style={{ fontFamily: "'Rubik', sans-serif" }}>
                  Gateway
                </span>
              </div>
              <div
                className="hidden md:flex items-center justify-center mb-6"
              >
                <span className="inline-flex items-center gap-2 rounded-full border border-cyan-400/20 bg-cyan-400/10 px-4 py-1.5 text-[11px] uppercase tracking-[0.22em] text-cyan-300/90">
                  <Wand2 className="w-3.5 h-3.5" />
                  Neural Learning Studio
                </span>
              </div>
              <h1
                className="text-5xl md:text-7xl lg:text-[100px] font-extrabold tracking-tight leading-[0.9] text-white mb-2 md:mb-1 drop-shadow-2xl"
                style={{ fontFamily: "'Rubik', sans-serif" }}
              >
                Your Infinite
              </h1>
              <span
                className="text-3xl md:text-5xl lg:text-7xl font-bold tracking-tight bg-gradient-to-b from-white/60 to-white/20 bg-clip-text text-transparent block drop-shadow-sm mb-8 pb-3"
                style={{ fontFamily: "'Rubik', sans-serif" }}
              >
                Knowledge Engine
              </span>
              <div
                className="hidden md:block absolute -inset-x-8 -bottom-10 h-24 bg-gradient-to-r from-cyan-400/0 via-cyan-400/15 to-cyan-400/0 blur-3xl"
              />
            </div>

            <p
              className="text-white/40 text-[15px] md:text-sm max-w-xl leading-relaxed mb-10 md:mb-8 font-light px-4"
            >
              Generate personalized learning guides with AI. Choose your mode, define your topic, and master any subject instantly.
            </p>

            <div className="flex flex-col sm:flex-row items-center gap-4 w-full sm:w-auto">
              <button
                onClick={onGetStarted}
                className="w-full sm:w-auto relative z-10 px-8 py-3 bg-white/5 hover:bg-white/10 border border-white/10 hover:border-white/20 rounded-full text-[13px] font-medium tracking-wide text-white/90 hover:text-white transition-all group flex items-center justify-center gap-2 shadow-[0_0_30px_rgba(255,255,255,0.05)] hover:shadow-[0_0_50px_rgba(255,255,255,0.1)]"
              >
                <span>Start Learning Now</span>
                <MoveRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </button>
            </div>
          </div>
        );
    }
  };

  const renderMobileContent = () => {
    switch (activeTab) {
      case 'street':
        return (
          <section className="space-y-4 rounded-3xl border border-cyan-400/20 bg-cyan-500/[0.07] p-5">
            <p className="text-xs font-semibold uppercase tracking-[0.25em] text-cyan-300/80">Street Mode</p>
            <h2 className="text-3xl font-semibold text-white" style={{ fontFamily: "'Rubik', sans-serif" }}>Speak. Act. Win.</h2>
            <p className="text-sm leading-relaxed text-white/70">High-energy, direct writing that drives immediate execution and removes fluff.</p>
            <div className="grid grid-cols-1 gap-3">
              {['No-BS tone', 'Fast tactical playbooks', 'Momentum-first writing'].map((item) => (
                <div key={item} className="rounded-2xl border border-cyan-300/20 bg-black/30 px-4 py-3 text-sm text-white/80">{item}</div>
              ))}
            </div>
          </section>
        );
      case 'stellar':
        return (
          <section className="space-y-4 rounded-3xl border border-purple-400/20 bg-purple-500/[0.07] p-5">
            <p className="text-xs font-semibold uppercase tracking-[0.25em] text-purple-300/80">Stellar Mode</p>
            <h2 className="text-3xl font-semibold text-white" style={{ fontFamily: "'Rubik', sans-serif" }}>Learn in Systems.</h2>
            <p className="text-sm leading-relaxed text-white/70">Structured, research-like books designed for deep understanding and clarity.</p>
            <div className="grid grid-cols-1 gap-3">
              {['Framework-driven chapters', 'Concept depth + examples', 'Built for focused study'].map((item) => (
                <div key={item} className="rounded-2xl border border-purple-300/20 bg-black/30 px-4 py-3 text-sm text-white/80">{item}</div>
              ))}
            </div>
          </section>
        );
      case 'process':
        return (
          <section className="space-y-4 rounded-3xl border border-white/10 bg-white/[0.04] p-5">
            <p className="text-xs font-semibold uppercase tracking-[0.25em] text-white/60">How it works</p>
            <h2 className="text-3xl font-semibold text-white" style={{ fontFamily: "'Rubik', sans-serif" }}>From Idea to Book.</h2>
            <div className="space-y-3">
              {[
                'Describe your topic in one line',
                'Choose Street or Stellar writing mode',
                'Generate a polished guide in seconds'
              ].map((step, idx) => (
                <div key={step} className="flex items-start gap-3 rounded-2xl border border-white/10 bg-black/30 p-3.5">
                  <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-white/10 text-xs font-bold text-white">{idx + 1}</span>
                  <p className="text-sm text-white/80">{step}</p>
                </div>
              ))}
            </div>
          </section>
        );
      case 'demo':
        return (
          <section className="space-y-4 rounded-3xl border border-white/10 bg-white/[0.04] p-5">
            <div className="flex gap-2">
              {DEMO_BOOKS.map((book, i) => (
                <button
                  key={book.id}
                  onClick={() => setActiveDemoIdx(i)}
                  className={`rounded-full px-4 py-2 text-xs font-bold uppercase tracking-[0.15em] ${activeDemoIdx === i ? 'bg-white text-black' : 'border border-white/15 text-white/70'}`}
                >
                  {book.mode}
                </button>
              ))}
            </div>
            <h2 className="text-2xl font-semibold text-white" style={{ fontFamily: "'Rubik', sans-serif" }}>{activeBook.shortTitle}</h2>
            <p className="text-sm leading-relaxed text-white/70">{activeBook.desc}</p>
            <a href={activeBook.url} target="_blank" rel="noopener noreferrer" className="flex w-full items-center justify-center gap-2 rounded-2xl bg-white py-3 text-xs font-semibold uppercase tracking-[0.14em] text-black">
              <HardDriveDownload className="h-3.5 w-3.5" />
              Download sample PDF
            </a>
          </section>
        );
      case 'features':
        return (
          <section className="space-y-4 rounded-3xl border border-emerald-400/20 bg-emerald-500/[0.06] p-5">
            <p className="text-xs font-semibold uppercase tracking-[0.25em] text-emerald-300/80">Capabilities</p>
            <h2 className="text-3xl font-semibold text-white" style={{ fontFamily: "'Rubik', sans-serif" }}>Why Pustakam</h2>
            <div className="space-y-3">
              {['Generate complete guides in seconds', 'Structured chapters, modules and quizzes', 'Covers technical and non-technical topics'].map((item) => (
                <div key={item} className="rounded-2xl border border-emerald-300/20 bg-black/30 px-4 py-3 text-sm text-white/85">{item}</div>
              ))}
            </div>
          </section>
        );
      default:
        return (
          <section className="space-y-5 rounded-3xl border border-white/10 bg-white/[0.04] p-5">
            <p className="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300/80">AI Learning Studio</p>
            <h1 className="text-4xl font-semibold leading-tight text-white" style={{ fontFamily: "'Rubik', sans-serif" }}>
              Your Infinite
              <span className="block text-white/60">Knowledge Engine</span>
            </h1>
            <p className="text-sm leading-relaxed text-white/70">Generate professional learning books with layouts optimized for quick mobile reading.</p>
            <div className="grid grid-cols-2 gap-3 text-center">
              <div className="rounded-2xl border border-white/10 bg-black/30 p-3">
                <p className="text-lg font-semibold text-white">2</p>
                <p className="text-[11px] uppercase tracking-wide text-white/50">Writing Modes</p>
              </div>
              <div className="rounded-2xl border border-white/10 bg-black/30 p-3">
                <p className="text-lg font-semibold text-white">1 Click</p>
                <p className="text-[11px] uppercase tracking-wide text-white/50">PDF Export</p>
              </div>
            </div>
            <button
              onClick={onGetStarted}
              className="flex w-full items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3 text-xs font-semibold uppercase tracking-[0.14em] text-black"
            >
              Start Learning
              <MoveRight className="h-4 w-4" />
            </button>
          </section>
        );
    }
  };

  const mobileTabs = [
    { id: 'home', label: 'Home', icon: Home },
    { id: 'process', label: 'Process', icon: Compass },
    { id: 'street', label: 'Street', icon: Flame },
    { id: 'stellar', label: 'Stellar', icon: Sparkles },
    { id: 'demo', label: 'Demo', icon: BookOpen },
    { id: 'features', label: 'Features', icon: Layers3 },
  ];

  // --- MAIN RENDER ---
  return (
    <div className="h-screen w-screen bg-black text-white selection:bg-white/20 selection:text-white overflow-hidden font-sans flex flex-col relative">
      <NebulaBackground />

      {/* Promo Banner */}
      {showPromo && (
        <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} className="absolute top-24 right-6 z-50 hidden md:block">
          <div className="flex items-center gap-3 pl-4 pr-10 py-3 bg-cyan-950/40 backdrop-blur-md border border-cyan-500/20 rounded-xl shadow-2xl relative group hover:border-cyan-500/40 transition-colors">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-cyan-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-cyan-500"></span>
            </span>
            <div className="flex flex-col">
              <span className="text-cyan-400 text-xs font-bold tracking-wider uppercase">Limited Offer</span>
              <span className="text-white text-xs font-medium">1 Year Free Membership</span>
            </div>
            <button onClick={handleDismissPromo} className="absolute top-2 right-2 p-1 text-white/20 hover:text-white/80 hover:bg-white/10 rounded-full transition-all">
              <X size={12} />
            </button>
          </div>
        </motion.div>
      )}

      {/* Header - UPDATED: Gradient background fixed and mobile height reduced */}
      <header className="fixed top-0 left-0 right-0 z-50 px-5 md:px-6 py-2.5 md:py-4 flex items-center justify-between gap-4 pointer-events-none border-b border-white/10 bg-gradient-to-b from-black/95 via-black/75 to-transparent backdrop-blur-md pb-5" style={{ paddingTop: 'calc(env(safe-area-inset-top) + 0.625rem)' }}>
        <div className="flex items-center gap-2 cursor-pointer group pointer-events-auto select-none" onClick={() => handleTabChange('home')}>
          <img src="/white-logo.png" alt="Pustakam AI Logo" className="w-[33px] h-[33px] md:w-8 md:h-8 opacity-90 transition-opacity group-hover:opacity-100" />
          <span className="text-white/90 font-bold text-[16px] md:text-xl tracking-tight group-hover:text-white transition-colors">
            Pustakam<span className="text-white/40 group-hover:text-white/60 transition-colors"> X</span>
          </span>
        </div>

        <div className="flex items-center gap-2.5 md:gap-3">
          <button onClick={onGetStarted} className="focus-ring md:hidden pointer-events-auto bg-white text-black px-4 py-2 rounded-full text-[10px] font-semibold tracking-[0.08em] uppercase hover:bg-white/90 transition-all shadow-[0_0_15px_rgba(255,255,255,0.1)]">
            Start
          </button>
          <button onClick={() => setMobileMenuOpen(true)} className="md:hidden pointer-events-auto p-2.5 text-white/70 hover:text-white bg-white/5 rounded-full border border-white/15 backdrop-blur-md">
            <Menu size={18} />
          </button>
        </div>

        <nav className="hidden md:flex pointer-events-auto items-center p-1.5 bg-white/[0.05] rounded-full border border-white/10 backdrop-blur-xl shadow-[0_18px_40px_-26px_rgba(0,0,0,0.7)] relative mx-auto">
          {[
            { id: 'home', label: 'Home' },
            { id: 'process', label: 'How it Works' },
            { id: 'street', label: 'Street Mode' },
            { id: 'stellar', label: 'Stellar Mode' },
            { id: 'demo', label: 'Demo' },
            { id: 'features', label: 'Use Cases' },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => handleTabChange(tab.id as any)}
              className={`relative px-5 py-2 rounded-full text-[11px] font-medium tracking-widest uppercase transition-colors duration-200 whitespace-nowrap z-10 ${activeTab === tab.id ? 'text-white' : 'text-white/40 hover:text-white/70'
                }`}
            >
              {activeTab === tab.id && (
                <motion.div
                  layoutId="activeTab"
                  className="absolute inset-0 bg-white/10 rounded-full shadow-[0_0_15px_rgba(255,255,255,0.1)] border border-white/5"
                  transition={{ type: 'spring', bounce: 0.2, duration: 0.6 }}
                />
              )}
              <span className="relative z-10">{tab.label}</span>
            </button>
          ))}
        </nav>

        <div className="hidden md:flex pointer-events-auto items-center gap-3.5">
          <button onClick={onLogin} className="text-[11px] font-semibold tracking-[0.12em] text-white/60 hover:text-white transition-colors uppercase">Login</button>
          <button
            onClick={onGetStarted}
            className="bg-white text-black px-6 py-2.5 rounded-full text-[11px] font-bold tracking-widest uppercase hover:bg-white/90 transition-all shadow-[0_0_20px_rgba(255,255,255,0.15)] hover:shadow-[0_0_30px_rgba(255,255,255,0.3)] hover:scale-105 active:scale-95"
          >
            Try Pustakam
          </button>
        </div>
      </header>

      {/* Mobile Menu Overlay */}
      <AnimatePresence>
        {mobileMenuOpen && (
          <motion.div
            initial={{ clipPath: 'circle(0% at calc(100% - 40px) 40px)', opacity: 0 }}
            animate={{ clipPath: 'circle(150% at calc(100% - 40px) 40px)', opacity: 1 }}
            exit={{ clipPath: 'circle(0% at calc(100% - 40px) 40px)', opacity: 0 }}
            transition={{ type: 'spring', damping: 25, stiffness: 120, duration: 0.8 }}
            className="fixed inset-0 z-[100] bg-black/95 backdrop-blur-xl flex flex-col p-8 pointer-events-auto origin-top-right"
          >
            <div className="flex items-center justify-between mb-16">
              <div className="flex items-center gap-3">
                <img src="/white-logo.png" alt="Logo" className="w-8 h-8" />
                <div className="flex flex-col">
                  <span className="text-white font-bold text-sm tracking-tight leading-none uppercase">PustakamAI</span>
                  <span className="text-white/25 text-[10px] uppercase tracking-[0.22em] font-semibold leading-none mt-1">Intelligence Layer</span>
                </div>
              </div>
              <button onClick={() => setMobileMenuOpen(false)} className="p-2 text-white hover:text-white/70 transition-colors">
                <X size={32} strokeWidth={2} />
              </button>
            </div>

            <div className="flex flex-col gap-8 mb-16">
              {[
                { id: 'street', label: 'STREET', action: () => handleTabChange('street') },
                { id: 'stellar', label: 'STELLAR', action: () => handleTabChange('stellar') },
                {
                  id: 'disclaimer',
                  label: 'DISCLAIMER',
                  action: () => {
                    setMobileMenuOpen(false);
                    onShowDisclaimer?.();
                  }
                },
                {
                  id: 'compliance',
                  label: 'COMPLIANCE',
                  action: () => {
                    setMobileMenuOpen(false);
                    onShowCompliance?.();
                  }
                },
              ].map((tab, idx) => (
                <motion.button
                  key={tab.id}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.1 * idx, duration: 0.4 }}
                  onClick={tab.action}
                  className={`text-left text-3xl font-semibold tracking-tight transition-colors duration-300 ${(tab.id === 'street' || tab.id === 'stellar')
                    ? (activeTab === tab.id ? 'text-white' : 'text-white/35 hover:text-white')
                    : 'text-white/65 hover:text-white'
                    }`}
                  style={{ fontFamily: "'Rubik', sans-serif" }}
                >
                  {tab.label}
                </motion.button>
              ))}
            </div>

            <div className="mt-auto bg-white/5 border border-white/10 rounded-[40px] p-8 pb-10 flex flex-col gap-6 backdrop-blur-md">
              <div className="flex flex-col gap-2">
                <span className="text-white/45 text-[10px] uppercase tracking-[0.28em] font-semibold mb-1">Quick Links</span>
                <button onClick={() => { setMobileMenuOpen(false); onShowBlog?.(); }} className="text-left text-white/60 text-lg font-medium hover:text-white transition-colors py-1">Blog</button>
                <button onClick={() => { setMobileMenuOpen(false); onShowAbout?.(); }} className="text-left text-white/60 text-lg font-medium hover:text-white transition-colors py-1">About</button>
              </div>
              <button onClick={() => { setMobileMenuOpen(false); onGetStarted(); }} className="text-left text-cyan-400 text-xl font-bold hover:text-cyan-300 transition-colors flex items-center gap-2">
                <span>Get Started Now</span>
                <MoveRight size={20} />
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main Content Area */}
      <main className="flex-1 flex flex-col relative z-10 md:pt-16 overflow-hidden md:overflow-visible">
        <div className="h-full flex-1 flex flex-col items-center justify-start md:justify-center pt-16 md:pt-0 relative w-full">

          {/* Mobile Specific Scrollable Content (Grid Layout) */}
          <div className="md:hidden w-full h-full overflow-hidden flex flex-col px-4 pb-4">
            <div className="mx-auto w-full max-w-md flex flex-col h-full">
              <div className="relative z-20 mb-4 rounded-2xl border border-white/10 bg-black/35 p-2.5 backdrop-blur-xl shadow-[0_20px_50px_rgba(0,0,0,0.35)]">
                <div className="grid grid-cols-3 gap-2">
                  {mobileTabs.map((tab) => {
                    const Icon = tab.icon;
                    return (
                      <button
                        key={tab.id}
                        onClick={() => handleTabChange(tab.id as any)}
                        className={`min-h-[62px] rounded-xl border px-2 py-2 text-[9px] font-semibold uppercase tracking-[0.14em] transition-all duration-300 ${activeTab === tab.id
                          ? 'border-white/80 bg-white text-black shadow-[0_6px_20px_rgba(255,255,255,0.18)]'
                          : 'border-white/10 bg-white/[0.03] text-white/75 hover:border-white/30 hover:bg-white/[0.08]'
                          }`}
                      >
                        <span className="flex flex-col items-center justify-center gap-1.5">
                          <Icon className="h-3.5 w-3.5" />
                          <span>{tab.label}</span>
                        </span>
                      </button>
                    );
                  })}
                </div>
              </div>
              <div
                className="flex-1 overflow-y-auto pr-1"
                style={{
                  maskImage: 'linear-gradient(to bottom, transparent, black 40px, black calc(100% - 40px), transparent)',
                  WebkitMaskImage: 'linear-gradient(to bottom, transparent, black 40px, black calc(100% - 40px), transparent)'
                }}
              >
                <AnimatePresence mode="wait" custom={getDirection()}>
                  <motion.div
                    key={`mobile-${activeTab}`}
                    custom={getDirection()}
                    initial={{ opacity: 0, x: shouldReduceMotion ? 0 : getDirection() * 30 }}
                    animate={{ opacity: 1, x: 0, transition: { duration: 0.3, ease: [0.25, 0.46, 0.45, 0.94] } }}
                    exit={{ opacity: 0, x: shouldReduceMotion ? 0 : getDirection() * -20, transition: { duration: 0.2, ease: [0.55, 0, 1, 0.45] } }}
                    className="py-4"
                  >
                    {renderMobileContent()}
                  </motion.div>
                </AnimatePresence>
              </div>
            </div>
          </div>

          {/* Desktop Content - UPDATED: Direction-aware sliding animation */}
          <div className="hidden md:flex w-full h-full flex-1 flex-col items-center justify-center">
            <AnimatePresence mode="wait" custom={getDirection()}>
              <motion.div
                key={activeTab}
                custom={getDirection()}
                variants={landingDesktopVariants}
                initial="enter"
                animate="center"
                exit="exit"
                className="w-full flex-1 flex flex-col items-center justify-center"
              >
                {renderContent()}
              </motion.div>
            </AnimatePresence>
          </div>

          {/* Footer */}
          <footer className="w-full px-6 py-4 md:py-5 border-t border-white/10 bg-gradient-to-t from-black/95 via-black/88 to-black/70 md:backdrop-blur-xl md:absolute md:bottom-0 md:left-0 md:right-0 z-50">
            <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 md:gap-3">
              <div className="flex items-center gap-4 text-[10px] md:text-[11px] font-medium tracking-wide meta-secondary uppercase">
                <span>(c) {new Date().getFullYear()} Pustakam X</span>
                <span className="hidden md:inline">|</span>
                <span>Tanmay Kalbande</span>
              </div>

              <div className="flex items-center gap-6 md:gap-6 w-auto">
                <div className="flex items-center gap-5 md:gap-5">
                  <a href="https://x.com/404NotTelling" target="_blank" rel="noopener noreferrer" className="text-white/30 hover:text-white transition-colors">
                    <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
                    </svg>
                  </a>
                  <a href="https://github.com/tanmay-kalbande" target="_blank" rel="noopener noreferrer" className="text-white/30 hover:text-white transition-colors">
                    <svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z" />
                    </svg>
                  </a>
                  <a href="https://www.linkedin.com/in/tanmay-kalbande/" target="_blank" rel="noopener noreferrer" className="text-white/30 hover:text-white transition-colors">
                    <svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.266 2.37 4.266 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
                    </svg>
                  </a>
                </div>
                <div className="h-3 w-px bg-white/10 hidden md:block" />
                <div className="flex items-center gap-4 md:gap-5">
                  <button onClick={onShowBlog} className="focus-ring text-[10px] md:text-[11px] font-medium tracking-wide meta-secondary hover:text-white uppercase transition-colors">Blog</button>
                  <button onClick={onShowAbout} className="focus-ring text-[10px] md:text-[11px] font-medium tracking-wide meta-secondary hover:text-white uppercase transition-colors">About</button>
                  <button onClick={onShowPrivacy} className="focus-ring text-[10px] md:text-[11px] font-medium tracking-wide meta-secondary hover:text-white uppercase transition-colors">Privacy</button>
                  <button onClick={onShowTerms} className="focus-ring text-[10px] md:text-[11px] font-medium tracking-wide meta-secondary hover:text-white uppercase transition-colors">Terms</button>
                </div>
              </div>
            </div>
          </footer>

        </div>
      </main>
    </div>
  );
};

export default LandingPage;


